### ISSUE TITLE
[AN] feat: To-Do 리스트 api 호출 로직 구현

### ISSUE THREAD

**Issue by saesang** [DKU-Dgaja/gitudy#347]
## 어떤 기능인가요?

 To-Do 상세페이지에서 To-Do 리스트 api를 호출하여 리스트로 나타내는 로직을 구현한다.
- 호출 api: /study/{studyInfoId}/todo

## 작업 상세 내용

- [ ] To-Do 리스트와 커밋 item 관련 UI 구현 
- [ ] To-Do 리스트 관련 adapter 구현
- [ ] Activity 내 To-Do 리스트 및 커밋 리스트 로직 구현
