### ISSUE TITLE
[AN] feat: to-do 기능 추가 및 수정

### ISSUE THREAD

**Issue by saesang** [DKU-Dgaja/gitudy#434]
## 어떤 기능인가요?

to-do 기능 로직 및 UI를 추가 및 수정한다.

## 작업 상세 내용

- [x] to-do 수정 기능 구현
- [x] to-do 삭제 기능 구현
- [x] to-do progress bar 관련 기능 수정
